### ISSUE TITLE
No Connection to https://parsers.org/download/congocc-full.jar

### ISSUE THREAD

**Issue by stbischof** [congo-cc/congo-parser-generator#19]
all https://www.parsers.org/ is down

**Comment by revusky** [comment]
Hmm, that is strange. It seems like it doesn't work if you write `www.parsers.org`. It has to be `parsers.org`. Of course, it should work with the www. I'll look into this shortly. Thanks for reporting this.

**Comment by revusky** [comment]
I think it's fixed now. By all means try it from your end.
