### ISSUE TITLE
[typo] fix congocc.org/download urls

### ISSUE THREAD

**Issue by stbischof** [congo-cc/congo-parser-generator#2]
Wiki:
The [Wiki](https://github.com/congo-cc/congo-parser-generator/wiki/Migrating-to-CongoCC-(from-JavaCC-21)) page uses the wrong link for the jar.

https://congocc.jar/download/congocc-full.jar vs.
https://congocc.org/download/congocc-full.jar

Forum:
https://discuss.congocc.org/d/30-migrating-to-congocc-any-snags-should-be-quite-minor

Code:
[Main.java](https://github.com/congo-cc/congo-parser-generator/blob/981fc97716511a80a413acf012f3c491e36be833/src/java/org/congocc/Main.java#L73)

"https://congocc.com/download/" vs.
"https://congocc.org/download/"

**Comment by revusky** [comment]
Thanks a lot for telling me about this! Much appreciated.

**Comment by stbischof** [comment]
open source is teamwork;-)
