### ISSUE TITLE
Reproducible build - avoid changing method and imports order

### ISSUE THREAD

**Issue by stbischof** [congo-cc/congo-parser-generator#34]
When build twice the order of the Imports in the Parser and the order of the methods change between two builds with same grammar.

**Comment by revusky** [comment]
If you try now, with the latest code, do you still have this problem?

**Comment by stbischof** [comment]
will build maven snapshot and test it in next hours.

**Comment by stbischof** [comment]
still in other order each time.

but https://parsers.org/download/congocc-full.jar .  is from 20.04.
 maybe this does not hold the changes?

**Comment by revusky** [comment]
> but https://parsers.org/download/congocc-full.jar . is from 20.04. maybe this does not hold the changes=

Well, no, it doesn't. (Or didn't. Now it does.)

You would have had to do (from the top-level directory where you checked out the code)
     git pull
     ant full-jar

**Comment by stbischof** [comment]
Still exist with build of 25.04.

**Comment by stbischof** [comment]
@revusky could you please release the Version to the Server?

**Comment by revusky** [comment]
> @revusky could you please release the Version to the Server?

It is done.

You can also build with:

       git clone https://github.com/congo-cc/congo-parser-generator.git congo 
       cd congo
       ant full-jar

**Comment by stbischof** [comment]
Yes i build it this way Multiple times for the pr. But the maven build starts with a Download ;)

**Comment by revusky** [comment]
Actually, I just quickly went through and reverted some of the cases where it is glaringly obvious that it makes no difference if you use LinkedHashSet/Map or just the regular one. (Certainly, if you never iterate over the keys, it just makes no difference that you used LinkedHashMap, say.) I put up the resulting jarfile on the server.

**Comment by stbischof** [comment]
Great!

**Comment by vsajip** [comment]
Shall I close this now?

**Comment by vsajip** [comment]
Closed, as no contrary feedback received.
