### ISSUE TITLE
LexerName should start with capital letter.

### ISSUE THREAD

**Issue by stbischof** [congo-cc/congo-parser-generator#5]
like the Parser the Lexer-ClassName should also start with a capital letter. (if grammer-file (basename) beginns with lowercase.

Parser does:
https://github.com/congo-cc/congo-parser-generator/blob/df784ca4a39b18ed65a4e7dc0e36203782a35f4d/src/java/org/congocc/Grammar.java#L342-L356

Lexer does not:

https://github.com/congo-cc/congo-parser-generator/blob/df784ca4a39b18ed65a4e7dc0e36203782a35f4d/src/java/org/congocc/Grammar.java#L373-L384

Quickfix for other, set `BASE_NAME`:
`BASE_NAME = My;`

**Comment by revusky** [comment]
Oh, sorry not to have answered sooner. I have been absorbed in some other things.

You're right, of course, the lexer class name should be deduced the same way as the parser class name, so if we have foo.ccc and we capitalize the 'f' for FooParser, we should also do so for FooLexer. I adjusted a bit how I dealt with this, so I think it works sensibly now. Here is [the relevant point in the code](https://github.com/congo-cc/congo-parser-generator/blob/main/src/java/org/congocc/Grammar.java#L327-L365).

**Comment by stbischof** [comment]
so we can close this here. Thank you!
