### ISSUE TITLE
Maven-Deployment and Maven-Plugin

### ISSUE THREAD

**Issue by stbischof** [congo-cc/congo-parser-generator#7]
I tried to find a way to male mvn releases and Maven-Plugin for congocc.
i created a repo with a small setup.
 
https://github.com/stbischof/ccc-mvn

maybe you could five me some ideas about this before i improve this/waste time.

Main Idea:
- create `org.congocc.parser.generator` as maven setup
- load `congocc-full.jar` jar from local or web URL. [see](https://github.com/stbischof/ccc-mvn/blob/a530a5b52590ff793a67194299a3e0fc857aa3e4/org.congocc.parser.generator/pom.xml#L18)
- create maven-mojo/maven-plugin [here](https://github.com/stbischof/ccc-mvn/blob/main/org.congocc.maven.plugin/src/main/java/org/congocc/maven/plugin/GeneratorMojo.java)
- create a simple test that uses maven plugin [here](https://github.com/stbischof/ccc-mvn/tree/main/org.congocc.testing.maven.plugin.simple)

----
*https://github.com/congo-cc/congo-parser-generator/commit/8101a2316a865f63db528581651de4ee5dd2406d not implemented - uses Main-Class: org.congocc.Main

**Comment by revusky** [comment]
Hi Stefan. I have not looked at this closely. I did create a repository within this "organization" to do the work. Here: https://github.com/congo-cc/ccc-mvn You should have received an invite.

**Comment by stbischof** [comment]
Thx. Now i know that i can go forward ans improve Work. More tomorrow.

**Comment by stbischof** [comment]
Just to be sure, you want the rest of the Project to be build with ant?

To that i just process the result?

**Comment by revusky** [comment]
> Just to be sure, you want the rest of the Project to be build with ant?

I do not want to change the build system internally at this moment.

Our goal right now is just to make it maximally easy for Maven users to use this.

**Comment by stbischof** [comment]
Ok this is what i wanted to do and will continue.

**Comment by stbischof** [comment]
This issue ist targeted for the coming week

**Comment by stbischof** [comment]
@revusky for a release to sonatype/maven central we need an account. so i think this must be done by you.?


https://theoverengineered.blog/posts/publishing-my-first-artifact-to-maven-central-using-github-actions

**Comment by revusky** [comment]
I just discovered that I already do have a sonatype account that I created about 3 years ago. (I tried to create a new account with username "revusky" and it said the name was taken.) I started the thing of creating a "New Project" issue. There is a field that is Username(s), which is:

> Comma separated list of the JIRA username(s) for yourself and anyone else you wish to be able to deploy artifacts to this groupId.

I would like you to add your username there. Do you have one? If not, it's easy enough to sign up for an account.

**Comment by stbischof** [comment]
Will sign tomorrow.

**Comment by revusky** [comment]
I think the group id will be org.congocc. 

I do own parsers.org and have been sort of wondering how to organize my various web stuff. I consider it all rather unsettled at the moment!  I have thought that discuss.congocc.org maybe should be discuss.parsers.org as that maybe suggests a more general discussion forum about parsers. And, yes, I did even consider making the main site for parsers.org instead of congocc.org. 

But I think the group id we'll use for congocc artifacts will just be org.congocc. Just a minute, I'll get that new project request submitted in a moment.

**Comment by revusky** [comment]
I just created the new project request. See: https://issues.sonatype.org/browse/OSSRH-89516
I guess they'll get back to us pretty soon.

**Comment by revusky** [comment]
Hi Stefan,

Do you now have what you need to proceed? Or do you need something else from me?

**Comment by stbischof** [comment]
Will process this this week

**Comment by stbischof** [comment]
First release so SNAPSHOT

https://s01.oss.sonatype.org/content/repositories/snapshots/org/congocc/

**Comment by stbischof** [comment]
further discussions on maven should be places here:
https://github.com/congo-cc/ccc-mvn
