### ISSUE TITLE
Is this a typo? It seems to subtract A - A

### ISSUE THREAD

**Issue by vsajip** [congo-cc/congo-parser-generator#90]
https://github.com/congo-cc/congo-parser-generator/blob/d174dc12c5cf1043be526aac42031bb03d9d87de/src/java/org/congocc/core/nfa/CompositeStateSet.java#L91-L93

**Comment by revusky** [comment]
Uhh, yeah, it must be a typo! I actually wrote this comparator explicitly so we would have deterministic ordering, I guess. As you surely surmise, it should almost certainly be `result = state1.getMoveRanges().size-state2.getMoveRanges().size();`
